---
galaxy_info:
  author: Alexandr Romanin
  description: Test application deployment
  license: "license (BSD, MIT)"

  min_ansible_version: 2.4

  platforms:
    - name: Ubuntu
      versions:
        - all

  galaxy_tags: []

dependencies: []
